@extends('layouts.app')
@section('title', "Texas Hold'em contra el Dealer — Lootra")

@section('styles')
<style>
    @keyframes card-deal{from{opacity:0;transform:translate(100px,-55px) rotate(14deg) scale(.7)}to{opacity:1;transform:none}}
    .dealer-table{background:radial-gradient(ellipse at 50% 42%,#176347,#06291e 68%);border:14px solid #4a220c;border-bottom-width:24px;box-shadow:inset 0 0 90px #0009,0 35px 80px #000b}
    .holdem-card{width:clamp(56px,8vw,82px);aspect-ratio:.7;border-radius:10px;background:linear-gradient(145deg,#fff,#e2e8f0);color:#111827;position:relative;box-shadow:0 12px 25px #0008;border:1px solid white;animation:card-deal .5s cubic-bezier(.16,1,.3,1) both}
    .holdem-card.red{color:#dc2626}.holdem-card.back{background:repeating-linear-gradient(45deg,#172554 0 6px,#7c3aed 6px 12px);border:4px solid white}
    .holdem-card b{position:absolute;left:7px;top:5px;font-size:16px}.holdem-card i{position:absolute;inset:0;display:grid;place-items:center;font-style:normal;font-size:30px}
    .phase-line::before{content:"";position:absolute;left:8%;right:8%;top:15px;height:2px;background:#ffffff12}.phase-step{position:relative;z-index:1}
</style>
@endsection

@section('contenido')
<div class="mx-auto max-w-[1450px] px-4 py-8" x-data="dealerPoker()">
    <header class="mb-6 flex flex-wrap items-center justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-[.2em] text-emerald-400">Poker por fases</p><h1 class="game-heading mt-1 font-black">Texas Hold'em contra el Dealer</h1><p class="mt-2 text-sm text-slate-500">Toma una decisión en cada calle y llega al showdown.</p></div><div class="flex gap-2"><a href="{{ route('arcade', ['game' => 'texas-holdem']) }}" class="rounded-xl border border-white/10 px-3 py-2 text-xs text-slate-400">Poker All-In</a><span class="rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-2 text-sm">Saldo <b class="ml-1 text-emerald-300" x-text="money(saldo)"></b></span></div></header>

    <div class="grid gap-6 xl:grid-cols-[1fr_330px]">
        <main>
            <div class="phase-line relative mb-5 grid grid-cols-5 text-center"><template x-for="(step,i) in ['Preflop','Flop','Turn','River','Showdown']"><div class="phase-step"><span class="mx-auto grid h-8 w-8 place-items-center rounded-full border text-xs font-black" :class="phaseIndex>=i?'border-emerald-300 bg-emerald-400 text-slate-950':'border-white/10 bg-[#0a0a12] text-slate-600'" x-text="i+1"></span><small class="mt-2 block text-[10px]" :class="phaseIndex>=i?'text-emerald-300':'text-slate-600'" x-text="step"></small></div></template></div>
            <section class="dealer-table relative min-h-[610px] overflow-hidden rounded-[3rem] p-6 sm:p-9">
                <div class="relative z-10 flex h-full min-h-[530px] flex-col justify-between">
                    <div class="text-center"><div class="mb-3 flex items-center justify-center gap-2"><b class="text-sm text-emerald-200">Dealer</b><span x-show="hand?.dealer_hand" class="rounded-full bg-black/25 px-2 py-1 text-xs text-amber-200" x-text="hand.dealer_hand"></span></div><div class="flex min-h-[118px] justify-center gap-2"><template x-for="(card,i) in dealerCards"><div class="holdem-card" :class="card.hidden?'back':cardColor(card)" :style="`animation-delay:${i*.12}s`"><template x-if="!card.hidden"><div><b x-text="rank(card.rank)"></b><i x-text="suit(card.suit)"></i></div></template></div></template></div></div>
                    <div class="rounded-3xl border border-emerald-200/15 bg-black/15 px-3 py-5 text-center"><p class="mb-3 text-[10px] font-black uppercase tracking-[.2em] text-emerald-200/60">Cartas comunitarias</p><div class="flex min-h-[105px] flex-wrap justify-center gap-2"><template x-for="(card,i) in communitySlots"><div class="holdem-card" :class="card.placeholder?'border-dashed !bg-white/5 opacity-30':cardColor(card)" :style="`animation-delay:${i*.1}s`"><template x-if="!card.placeholder"><div><b x-text="rank(card.rank)"></b><i x-text="suit(card.suit)"></i></div></template></div></template></div></div>
                    <div class="text-center"><div class="mb-3 flex items-center justify-center gap-2"><b class="text-sm text-emerald-200">Tu mano</b><span x-show="hand?.player_hand" class="rounded-full bg-black/25 px-2 py-1 text-xs text-cyan-200" x-text="hand.player_hand"></span></div><div class="flex min-h-[118px] justify-center gap-2"><template x-for="(card,i) in (hand?.player||[])"><div class="holdem-card" :class="cardColor(card)" :style="`animation-delay:${i*.12}s`"><b x-text="rank(card.rank)"></b><i x-text="suit(card.suit)"></i></div></template><template x-if="!hand"><div class="flex gap-2"><div class="holdem-card back opacity-40"></div><div class="holdem-card back opacity-40"></div></div></template></div></div>
                </div>
            </section>
            <div x-show="finished" class="mt-5 rounded-2xl border p-5 text-center" :class="hand?.result==='ganada'?'border-emerald-400/30 bg-emerald-400/10':hand?.result==='empate'?'border-amber-400/30 bg-amber-400/10':'border-red-400/20 bg-red-400/5'"><h2 class="text-2xl font-black capitalize" x-text="hand?.result"></h2><p class="mt-1 text-sm text-slate-400"><span x-text="hand?.player_hand"></span> contra <span x-text="hand?.dealer_hand"></span></p><b x-show="hand?.winnings>0" class="mt-2 block text-emerald-300" x-text="'Recibes '+money(hand.winnings)"></b></div>
        </main>

        <aside class="space-y-5">
            <section class="rounded-2xl border border-white/10 bg-white/[.035] p-5"><p class="text-[10px] font-black uppercase tracking-[.2em] text-brand-400" x-text="hand?'Decisión actual':'Nueva partida'"></p><h2 class="mt-1 text-lg font-black" x-text="instruction"></h2>
                <template x-if="!hand||finished"><div class="mt-4"><label class="text-xs text-slate-500">Ante inicial</label><div class="mt-2 flex items-center rounded-xl border border-white/10 bg-black/20 px-3"><span>€</span><input x-model.number="ante" type="number" min="1" max="1000" class="w-full bg-transparent px-3 py-3 font-bold outline-none"></div><div class="mt-2 grid grid-cols-4 gap-1"><template x-for="v in [5,10,25,50]"><button @click="ante=v" class="rounded-lg bg-white/5 py-2 text-xs hover:bg-white/10" x-text="v+'€'"></button></template></div><button @click="start" :disabled="busy||ante>saldo" class="mt-4 w-full rounded-xl bg-gradient-to-r from-emerald-400 to-cyan-400 py-3.5 font-black text-slate-950 disabled:opacity-40">Repartir nueva mano</button></div></template>
                <template x-if="hand&&!finished"><div class="mt-4"><div class="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><div class="flex justify-between"><span class="text-slate-500">Ante</span><b x-text="money(hand.ante)"></b></div><div class="mt-2 flex justify-between"><span class="text-slate-500">Total en mesa</span><b class="text-amber-300" x-text="money(hand.wagered)"></b></div></div><template x-if="hand.phase==='preflop'"><div class="mt-4 space-y-2"><button @click="act('jugar')" :disabled="busy||hand.ante>saldo" class="w-full rounded-xl bg-emerald-500 py-3 font-black text-slate-950">Jugar · añadir <span x-text="money(hand.ante)"></span></button><button @click="act('retirarse')" :disabled="busy" class="w-full rounded-xl bg-white/5 py-3 font-bold text-slate-400">Retirarme</button><p class="text-xs leading-relaxed text-slate-500">Jugar iguala el ante y revela el flop. Retirarte termina la mano sin cobrar más.</p></div></template><template x-if="hand.phase!=='preflop'"><div class="mt-4 space-y-2"><button @click="act('continuar')" :disabled="busy" class="w-full rounded-xl bg-cyan-400 py-3 font-black text-slate-950" x-text="nextLabel"></button><button x-show="hand.phase!=='river'" @click="act('retirarse')" :disabled="busy" class="w-full rounded-xl bg-white/5 py-2.5 text-sm text-slate-500">Retirarme</button></div></template></div></template>
                <p x-show="error" class="mt-3 rounded-lg bg-red-500/10 p-2 text-center text-xs text-red-300" x-text="error"></p>
            </section>
            <section class="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h3 class="font-bold">Cómo se juega</h3><ol class="mt-3 space-y-3 text-xs text-slate-400"><li><b class="text-white">1.</b> El ante reparte dos cartas para ti y dos ocultas al dealer.</li><li><b class="text-white">2.</b> Decide si juegas pagando otro ante o te retiras.</li><li><b class="text-white">3.</b> Revela flop, turn y river sin cargos adicionales.</li><li><b class="text-white">4.</b> La mejor mano de cinco cartas gana en el showdown.</li></ol></section>
        </aside>
    </div>
</div>

@push('scripts')
<script>
function dealerPoker(){return{hand:@js($activeHand),saldo:{{ auth()->user()->saldo }},ante:10,busy:false,error:'',get finished(){return ['finalizada','retirada'].includes(this.hand?.phase)},get phaseIndex(){return {preflop:0,flop:1,turn:2,river:3,finalizada:4,retirada:4}[this.hand?.phase]??0},get dealerCards(){return this.hand?.dealer||[{hidden:true},{hidden:true}]},get communitySlots(){return [...(this.hand?.community||[]),...Array(Math.max(0,5-(this.hand?.community?.length||0))).fill({placeholder:true})]},get instruction(){if(!this.hand||this.finished)return'Elige un ante fácil de controlar';return {preflop:'¿Juegas estas dos cartas?',flop:'Ya ves el flop',turn:'Se ha revelado el turn',river:'Última carta: vamos al showdown'}[this.hand.phase]},get nextLabel(){return {flop:'Revelar el turn',turn:'Revelar el river',river:'Ver showdown'}[this.hand?.phase]},money(v){return new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(v)||0)},rank(v){return({11:'J',12:'Q',13:'K',14:'A'})[v]||v},suit(v){return({S:'♠',H:'♥',D:'♦',C:'♣'})[v]},cardColor(c){return ['H','D'].includes(c.suit)?'red':''},async request(url,body){this.busy=true;this.error='';try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.message||'No se pudo completar la acción.');this.hand=d;this.saldo=Number(d.balance);this.$store.wallet.saldo=this.saldo;window.dispatchEvent(new CustomEvent('saldo-updated',{detail:{saldo:this.saldo}}));}catch(e){this.error=e.message}finally{this.busy=false}},start(){if(this.finished)this.hand=null;return this.request(@js(route('poker.dealer.start')),{ante:this.ante})},act(action){return this.request(@js(route('poker.dealer.action')),{accion:action})}}}
</script>
@endpush
@endsection
